<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Technology Department</name>
   <tag></tag>
   <elementGuidId>9c15a5c4-8c92-456f-b549-0bb0e8cff941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[180]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#52c734fc-bb27-437a-a0b4-13610c760fb2-187</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>81b35a55-126a-4455-a7b7-fc840dbc3cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>7f64381d-be56-4d8e-8062-69ecfe922f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8db26b69-89c8-4e84-9ed2-2b86bbb71049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>b12e6496-1066-437d-861e-0ce15942d4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>c7b0cc38-c4fa-44fc-8d66-dcb57f620de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-index</name>
      <type>Main</type>
      <value>179</value>
      <webElementGuid>211beea7-b5d1-43eb-b670-afc0b38f06d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-multiple-selection</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f2fbd5e1-25a1-4bfb-a223-60e4bd985ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>52c734fc-bb27-437a-a0b4-13610c760fb2-187</value>
      <webElementGuid>a57ebc38-b1bc-4bf6-a3fd-76a58e2c6edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>acf186a2-14f1-4aaa-8669-1739993f2425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>179</value>
      <webElementGuid>45ea979d-ee3c-4c61-a15c-0189c8461b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Technology Department</value>
      <webElementGuid>7d70fb78-be5f-42d9-9fa0-942981886c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;52c734fc-bb27-437a-a0b4-13610c760fb2-187&quot;)</value>
      <webElementGuid>47eb005e-d9df-49f6-96df-917dab94403a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='52c734fc-bb27-437a-a0b4-13610c760fb2-187']</value>
      <webElementGuid>0f2a4770-a513-49af-9e45-1371a116e834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='22f5b7e8-0cd5-48c9-b687-f1c68454a671']/li[180]</value>
      <webElementGuid>a5349a54-acef-4de1-bab3-f93c9b988a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYDistUser'])[1]/following::li[1]</value>
      <webElementGuid>cff88864-fa29-4bd5-ae8d-6208b348ef3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SY2'])[1]/following::li[2]</value>
      <webElementGuid>558a51cd-ea92-4e7c-a752-24e6956f9174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/preceding::li[1]</value>
      <webElementGuid>84ca0559-70bb-4641-982b-6e4b606037bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test01'])[1]/preceding::li[2]</value>
      <webElementGuid>865662f4-8bae-4f28-a770-d08a2b347915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Technology Department']/parent::*</value>
      <webElementGuid>fb47a897-f858-424e-b95c-7375a14c9ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[180]</value>
      <webElementGuid>f1ca82ec-0d80-4d75-a34c-ede305289943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '52c734fc-bb27-437a-a0b4-13610c760fb2-187' and (text() = 'Technology Department' or . = 'Technology Department')]</value>
      <webElementGuid>c8b8e363-1dea-4c95-b36b-de6d3378fffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
