<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TagNumber_assetTagNumber</name>
   <tag></tag>
   <elementGuidId>3cdeec75-a6a8-4453-b81a-067a9a4ab3f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='assetTagNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#assetTagNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13585a71-e989-4f28-bb6c-6a23073e3d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>4eabc80f-de5a-40dc-8b15-8882b7dc1a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>assetTagNumber</value>
      <webElementGuid>ee635a7a-0b85-4c0d-a574-6d96ea596413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assetTagNumber</value>
      <webElementGuid>a5ac550d-f249-483a-9a14-0003484c8d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0aeb528c-666d-450f-8fed-0abc3a1bc027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter tag number...</value>
      <webElementGuid>905c9a68-ed64-4384-ac4f-b238b567b148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assetTagNumber&quot;)</value>
      <webElementGuid>aee74a11-d46e-45d1-9300-1ac3e8805e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='assetTagNumber']</value>
      <webElementGuid>9cf31ca8-9748-492f-976e-b556a534af87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d07feac6-aa07-436e-b678-8e6ad12fb239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'assetTagNumber' and @type = 'text' and @placeholder = 'Please enter tag number...']</value>
      <webElementGuid>fb12f539-0ed1-4d5e-9468-69400c762005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
