<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_---3 fields</name>
   <tag></tag>
   <elementGuidId>9c143e37-f873-4bdf-8b33-c87dd9564a45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//view-my-tickets/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>201617d2-cd50-42ed-a85e-2867f6adcfbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-lg-12</value>
      <webElementGuid>4b2ee641-f627-494f-b8e6-3e7f289fde28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--- Sort By ---Show All Problem Types</value>
      <webElementGuid>e9a2775c-64b5-46a3-bc64-9f78cc0a3303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;ng-tns-0-0&quot;]/app-root[1]/div[@class=&quot;row gh-body gh-no-margin&quot;]/div[@class=&quot;col-sm-12 gh-body-container&quot;]/block-ui[1]/div[@class=&quot;block-container&quot;]/div[@class=&quot;content fullWidth delay minDuration&quot;]/div[@class=&quot;tab-panel&quot;]/dashboard[1]/div[1]/div[1]/div[@class=&quot;tab-pane&quot;]/div[2]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;offset-sm-1 col-sm-10 offset-sm-1&quot;]/view-my-tickets[1]/div[@class=&quot;row gh-my-tickets-row-mobile&quot;]/div[@class=&quot;col-lg-12&quot;]</value>
      <webElementGuid>fef421d4-ed8d-425a-987f-81c1e9fb661e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[2]/following::div[11]</value>
      <webElementGuid>d8855a34-b68f-406e-8d23-a27cc1f5ff1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[2]/following::div[11]</value>
      <webElementGuid>54d7c0a4-b26c-4f6c-88cf-b20002b5db6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//view-my-tickets/div/div</value>
      <webElementGuid>c3fcbabb-e47e-4766-b384-16bf6c89a7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '--- Sort By ---Show All Problem Types' or . = '--- Sort By ---Show All Problem Types')]</value>
      <webElementGuid>5da34934-770b-421e-9a8b-89f092e7f82c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
