<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_475</name>
   <tag></tag>
   <elementGuidId>231f64b0-919c-4ff7-ae52-6a153f005c04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[2]/following::div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9c1a9fb-3b0b-4805-85c7-2618ece238a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-chart-donut-center</value>
      <webElementGuid>8d70a1bb-73d9-4576-8db6-d2d36fc0b616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>475</value>
      <webElementGuid>5139fbb1-19d4-49ea-8f97-c00672f4b226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;ng-tns-0-0&quot;]/app-root[1]/div[@class=&quot;row gh-body gh-no-margin&quot;]/div[@class=&quot;col-sm-12 gh-body-container&quot;]/block-ui[1]/div[@class=&quot;block-container&quot;]/div[@class=&quot;content fullWidth delay minDuration&quot;]/div[@class=&quot;tab-panel&quot;]/dashboard[1]/div[1]/div[1]/div[@class=&quot;tab-pane&quot;]/div[@class=&quot;gh-hide-on-mobile&quot;]/chart-section[1]/div[@class=&quot;row gh-no-margin&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4 text-center&quot;]/donut-chart[1]/div[1]/kendo-chart[@class=&quot;k-chart k-widget&quot;]/div[@class=&quot;k-chart-donut-center&quot;]</value>
      <webElementGuid>0d6ba0f1-f157-42b6-86e7-088b768d2f43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[2]/following::div[5]</value>
      <webElementGuid>27919a67-238b-4bb8-ba13-f064fd9fd4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[2]/following::div[5]</value>
      <webElementGuid>62d48856-806f-4f19-9103-c56d340c7f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--- Sort By ---'])[1]/preceding::div[1]</value>
      <webElementGuid>6fe3640e-820e-4c62-904f-17b7b64b84fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show All Problem Types'])[1]/preceding::div[2]</value>
      <webElementGuid>d6e2aa31-f38b-4aa4-94e7-4bae8db2fbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/donut-chart/div/kendo-chart/div[2]</value>
      <webElementGuid>2082c9ff-0459-4ad0-8e2a-9c18bb069bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '475' or . = '475')]</value>
      <webElementGuid>3ba73221-d75b-4514-924e-cd955f335e21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
