<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0</name>
   <tag></tag>
   <elementGuidId>88165def-c3c7-40fa-b163-72079ee23744</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='My Tickets'])[3]/following::div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de1fe3ea-87c2-45e6-973c-ebe29f016886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-chart-donut-center</value>
      <webElementGuid>6f1423ef-fc68-4a00-a158-d56205f70345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5a9f4e78-a83e-4782-b9a4-167a7f6ae0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;ng-tns-0-0&quot;]/app-root[1]/div[@class=&quot;row gh-body gh-no-margin&quot;]/div[@class=&quot;col-sm-12 gh-body-container&quot;]/block-ui[1]/div[@class=&quot;block-container&quot;]/div[@class=&quot;content fullWidth delay minDuration&quot;]/div[@class=&quot;tab-panel&quot;]/dashboard[1]/div[1]/div[1]/div[@class=&quot;tab-pane&quot;]/div[@class=&quot;gh-hide-on-mobile&quot;]/chart-section[1]/div[@class=&quot;row gh-no-margin&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4 text-center&quot;]/donut-chart[1]/div[1]/kendo-chart[@class=&quot;k-chart k-widget&quot;]/div[@class=&quot;k-chart-donut-center&quot;]</value>
      <webElementGuid>4a5c8810-6ce4-485e-9a64-09c917f22deb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Tickets'])[3]/following::div[5]</value>
      <webElementGuid>735d0bd8-d365-4df2-935a-598c1d5514ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[1]/following::div[14]</value>
      <webElementGuid>e17e81e8-136b-415c-8077-5cd6cd0ff34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Tickets'])[3]/preceding::div[2]</value>
      <webElementGuid>a9c06174-985c-404e-8892-c1aa8780c4ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[2]/preceding::div[2]</value>
      <webElementGuid>36b3258d-82ee-4d09-a871-84a9535cf539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/donut-chart/div/kendo-chart/div[2]</value>
      <webElementGuid>eb49de7b-e264-403d-9313-cbe9b9a52cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0' or . = '0')]</value>
      <webElementGuid>51cbd9a9-e488-406f-8c02-7c43839ac4a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
