<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Problem Type</name>
   <tag></tag>
   <elementGuidId>2d1e40a0-f93f-46e2-8362-ee4cd560209a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='2fe166e6-6c9b-4b9e-94da-f2ad09a9581f-Problem Type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ef6cd0cd-1581-470d-a9ca-a1ce068b7119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>d51dc46a-ea00-44c0-b1b6-69d3eada37f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>dcfec4c0-3dc9-4b76-abf4-e83aec7740b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2fe166e6-6c9b-4b9e-94da-f2ad09a9581f-Problem Type</value>
      <webElementGuid>75c5f800-32d2-4a6a-9e88-e563d632ac0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f0b293dc-9204-4bc3-8472-d266f4dcc155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d6f02329-15e8-4bfb-8519-79ccab5fa2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Problem Type</value>
      <webElementGuid>0f4b59e1-1d58-4b85-bbad-cb0720a22f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2fe166e6-6c9b-4b9e-94da-f2ad09a9581f-Problem Type&quot;)</value>
      <webElementGuid>07c88760-5fce-4405-99dc-6fb1afe55870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='2fe166e6-6c9b-4b9e-94da-f2ad09a9581f-Problem Type']</value>
      <webElementGuid>3541a11c-e02d-4c21-83e9-87df322cf023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='9a2378b4-e89b-4ad0-bc85-4fb1ea1cafdd']/li[2]</value>
      <webElementGuid>51583541-161c-4fb4-b930-d600260b46d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[1]/following::li[1]</value>
      <webElementGuid>ff6195e0-fbad-45fd-b228-aebcdc3d8eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--- Sort By ---'])[2]/following::li[2]</value>
      <webElementGuid>b760f6e5-fe46-44df-a060-dc4c7689773b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recently Edited'])[1]/preceding::li[1]</value>
      <webElementGuid>07f8dd6d-5c6c-4347-a576-89c86719647d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::li[2]</value>
      <webElementGuid>fd152298-af20-405f-a1c8-fa793c94076f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Problem Type']/parent::*</value>
      <webElementGuid>194d45e7-7b9a-4c29-a0e6-7a7c5b006585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-list/div/ul/li[2]</value>
      <webElementGuid>9c837d05-b352-4dfd-9da6-cc046fb322ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '2fe166e6-6c9b-4b9e-94da-f2ad09a9581f-Problem Type' and (text() = 'Problem Type' or . = 'Problem Type')]</value>
      <webElementGuid>6a0b05ce-598a-41f3-b70d-2831ca64e552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
