<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_--- Sort By ---dropdown</name>
   <tag></tag>
   <elementGuidId>5ad5990f-d3ae-4110-bcdf-02f78faf0f90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-icon.k-i-arrow-s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4cb5fa50-29f2-44fa-b9c0-17b2d0664370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-s</value>
      <webElementGuid>d23dfd99-66c6-4a5e-b80f-0941235cc57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-0d28217c-f49b-4a7d-9666-f26afa1e3b82&quot;)/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-s&quot;]</value>
      <webElementGuid>fc157bb6-7b4b-4b40-af16-ecdb4c6d8988</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-0d28217c-f49b-4a7d-9666-f26afa1e3b82']/span[2]/span</value>
      <webElementGuid>443363ea-48df-4e87-8b4e-e916acb0f608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>85d5fd4b-1711-4acf-8731-fddacf5908a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
