<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_--- Sort By ---field</name>
   <tag></tag>
   <elementGuidId>4d2a30bc-9f0e-439c-95ec-ab7d026fc04a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='k-377e5c6c-ae63-4223-bb2f-2e57225ff1ff']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>77456b94-ccb7-4b35-a1d3-3d6f965c3a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>699e9afb-800b-411d-b4e7-1934f46fa716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0a41f990-3bd5-480e-9a03-ad2d479d5492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--- Sort By ---</value>
      <webElementGuid>1210e9c0-21b6-4ef2-b41c-3ac463233aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-377e5c6c-ae63-4223-bb2f-2e57225ff1ff&quot;)/span[@class=&quot;k-input&quot;]</value>
      <webElementGuid>f03e50e2-ea23-4400-bcae-dadc655d7367</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-377e5c6c-ae63-4223-bb2f-2e57225ff1ff']/span</value>
      <webElementGuid>82609efa-f6ae-4788-ad0c-a2578c65787f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[2]/following::span[2]</value>
      <webElementGuid>8b5557a6-0423-48cd-9d01-1ac3002eb1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[2]/following::span[2]</value>
      <webElementGuid>8778c43d-8529-40e0-91e8-2d232630cab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show All Problem Types'])[1]/preceding::span[3]</value>
      <webElementGuid>f787a3ba-780f-4614-8a06-6ddb67684bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reassign Ticket'])[1]/preceding::span[7]</value>
      <webElementGuid>f37c159d-6a3c-4a3d-aac4-f1e60bcf22ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='--- Sort By ---']/parent::*</value>
      <webElementGuid>208d5f5b-eb7d-42a5-87dc-25b4076b4220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>3d37fdbf-8471-42da-8bd4-20bce3beaaa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '--- Sort By ---' or . = '--- Sort By ---')]</value>
      <webElementGuid>7cbf351e-ec65-452c-8638-7fae68b90a17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
