<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All Tickets</name>
   <tag></tag>
   <elementGuidId>5f41febc-e2ae-4da3-be12-9a5508733f9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;viewTicketsSelection&quot;]/option[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#viewTicketsSelection</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5b96860f-209e-467c-af70-f909babb6cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-15-margin-left form-control pull-left gh-select-type-of-tickets-dropdown ng-tns-c16-0 ng-trigger ng-trigger-enterAnimationCloseButton ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>553b2458-3f38-45d8-9275-f7d5c6d0e006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>viewTicketsSelection</value>
      <webElementGuid>26553882-26d3-4b15-b0da-3fdc35430782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>93c05f90-f030-4812-9fd9-a3966d4b3174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View: All Tickets View: Active Tickets View: Inactive Tickets </value>
      <webElementGuid>bf7aeba0-70ee-457d-a228-9924ccf979cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewTicketsSelection&quot;)</value>
      <webElementGuid>0af88482-cc72-4dc0-aab6-2e34790f662b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='viewTicketsSelection']</value>
      <webElementGuid>04edcd05-99ce-4b9b-ae1b-1a5697f64337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tickets'])[2]/following::select[1]</value>
      <webElementGuid>f24f87ab-44ae-4acd-9eea-4b4612fdf26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[1]/preceding::select[1]</value>
      <webElementGuid>fea42ef6-4bec-40ad-8844-9cb913b3a2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//*[@id=&quot;viewTicketsSelection&quot;]/option[1]</value>
      <webElementGuid>ac357887-b3c7-4ed1-9d2d-1bef485f1128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
