<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Part Type</name>
   <tag></tag>
   <elementGuidId>80aa8b48-3499-413c-bb02-334872273e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//kendo-grid[@id='partsMainGrid']/div/table/tbody/tr/td[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>819caa43-994c-4ef1-a2bd-9ffe7ca7decc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pre</value>
      <webElementGuid>df8c3367-b2a6-451d-8c19-d22aab9d85b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> and </value>
      <webElementGuid>9d988ece-b1e8-4be4-adde-6b473b95a839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partsMainGrid&quot;)/div[@class=&quot;k-grid-aria-root&quot;]/table[1]/tbody[1]/tr[@class=&quot;k-master-row&quot;]/td[4]/div[@class=&quot;pre&quot;]</value>
      <webElementGuid>dd28af2c-037a-4fd5-a0ba-10fd9b5399e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='partsMainGrid']/div/table/tbody/tr/td[4]/div</value>
      <webElementGuid>2033e8d1-5fb6-4ffa-88a4-d36cce155826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='## AA Bulk parts - 33@'])[1]/following::div[1]</value>
      <webElementGuid>d90b7323-0045-482a-8945-7fcb6fd38f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='## AA Bulk parts -33'])[1]/following::div[2]</value>
      <webElementGuid>0900d500-3512-464d-ac63-21effbf30475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='## AA Bulk parts -0223'])[1]/preceding::div[5]</value>
      <webElementGuid>81079f79-be84-4f7b-a10d-34285c09fea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='## AA Bulk parts -0221'])[1]/preceding::div[6]</value>
      <webElementGuid>3ee9151b-1f86-4911-ab4c-1452abe550ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='and']/parent::*</value>
      <webElementGuid>1ca5bb49-245c-4f98-bed7-405358fd37b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div</value>
      <webElementGuid>f1bb12c9-e306-4b38-8479-42e415fe50b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' and ' or . = ' and ')]</value>
      <webElementGuid>72d2d9fd-b825-4830-b0c0-72c04f1efe02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
