<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit Part Name</name>
   <tag></tag>
   <elementGuidId>1c1ae418-1b5a-44cf-a9e8-5de6ed6f1add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#partName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='partName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03f4bd15-ca19-4a19-89b5-94079830477c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-ht-width ng-touched ng-dirty ng-invalid</value>
      <webElementGuid>37db0465-323d-44e9-bb6f-d268c5c69ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partName</value>
      <webElementGuid>a35b7e12-1dcc-413c-9bb4-270847d3a97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>583bf43b-b399-41fd-9592-d95ccdf16f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partName&quot;)</value>
      <webElementGuid>58ab4a58-e47a-4f7c-80fd-1d4ff35a5eef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partName']</value>
      <webElementGuid>6b33e71f-1438-4915-acca-7abc74636117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='partsMainGrid']/div/table/tbody/tr/td[3]/div/input</value>
      <webElementGuid>36da4b1f-7c30-4fb6-bc65-693b55553a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/input</value>
      <webElementGuid>d553f8c1-21d0-4c50-8a27-61e7c4351360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'partName']</value>
      <webElementGuid>bc6bf2e1-f842-47c4-912e-27607c3d88d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
