<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit Cost</name>
   <tag></tag>
   <elementGuidId>c9f05581-3f5e-4323-b960-0fdd3e713332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb8987f1-b815-4969-ad32-8475a229c675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-ht-width ng-valid ng-touched ng-dirty</value>
      <webElementGuid>00d93c3d-7181-44aa-826e-32c8bb19e8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cost</value>
      <webElementGuid>200df96c-fa3e-496a-a351-888d05d56be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9c7c4037-4b44-492b-a004-5ea9a5bf9b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>79413ccf-e879-4f5f-aabc-7c1cedc6123b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>d9349bab-66e5-4855-adbf-3b363992f1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>1b8c98bc-1aa6-4f6b-9595-9c6d234aac52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cost&quot;)</value>
      <webElementGuid>bd08f861-859c-4d18-948d-3a2d64090eb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cost']</value>
      <webElementGuid>15e5c140-0b0d-43d9-be0d-c07623734d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='partsMainGrid']/div/table/tbody/tr/td[7]/div/input</value>
      <webElementGuid>3bb6157e-551b-4981-9cd2-17dfd6580eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/input</value>
      <webElementGuid>246f7c1d-b29b-4f3f-affd-b3a6d39796e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cost' and @placeholder = '0']</value>
      <webElementGuid>6dc38080-04ee-4475-8b8f-a9d0bdb51355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
