<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit Part Number</name>
   <tag></tag>
   <elementGuidId>83f9426b-4022-42b5-bb1f-32db903ae16e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#partNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='partNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23e8f4f1-0ac2-45e7-add7-efb5029e930b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-ht-width ng-touched ng-dirty ng-invalid</value>
      <webElementGuid>3efa53a1-b51a-4df6-9949-d46049612038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partNumber</value>
      <webElementGuid>b597bba6-5c1c-4d2d-9ee2-166d7b83be17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>05c8bcdb-f87b-4a5d-830b-32a6c8a80651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partNumber&quot;)</value>
      <webElementGuid>42038a35-bc97-417d-82fe-aa9ca612d918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partNumber']</value>
      <webElementGuid>ce345955-8add-4469-868c-80e4d756a989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='partsMainGrid']/div/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>f74b2dde-36b0-423b-8e62-42a719421030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>8b58df48-8a66-4d95-9b01-0981bbf2dcb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'partNumber']</value>
      <webElementGuid>3a3948ba-9ba5-495a-b3e3-8730092bcaad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
