<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create Ticket</name>
   <tag></tag>
   <elementGuidId>09f39e79-770f-4484-9472-0065fc3a7c78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.gh-font-size-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='createTicketBtn']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4be0969b-fa1a-4209-9b32-84743536ea58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-font-size-medium</value>
      <webElementGuid>e68cc461-dee1-4f6f-a34d-3649a9ea28a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>bd283366-8f2c-4fcf-8adb-f4072d32dd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click To Add</value>
      <webElementGuid>55ab43fb-2047-4664-813d-8971f3b8eb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Create Ticket</value>
      <webElementGuid>e0e9aa84-acba-4b7e-99ae-5e9cfe557adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createTicketBtn&quot;)/a[@class=&quot;gh-font-size-medium&quot;]</value>
      <webElementGuid>a82d6dbd-ca84-47ef-90a9-32acc0df781e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='createTicketBtn']/a</value>
      <webElementGuid>fd6086d9-a9ea-43fc-9509-aad0e7ad5419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create Ticket')]</value>
      <webElementGuid>9130c1c1-fd76-4cee-ae01-e0215110b8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::a[1]</value>
      <webElementGuid>0b81fea6-4685-4465-b1bb-63f4e26a47fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RO'])[1]/following::a[2]</value>
      <webElementGuid>051bde2c-9709-43c1-9f38-78f8e67f9afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[2]</value>
      <webElementGuid>a1aa1e80-da66-46a9-a2ce-9ecc15a5d169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/a</value>
      <webElementGuid>10ee6a86-d8a2-4d9c-b17c-d6dc4dce88ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Click To Add' and (text() = ' Create Ticket' or . = ' Create Ticket')]</value>
      <webElementGuid>9cacbd1e-3fa2-4bd9-990b-7b012f5c7bce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
