<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All Articles</name>
   <tag></tag>
   <elementGuidId>ef618bc8-9ee4-49cb-9a11-2fa737882907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/div/ul/li[4]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>730c765e-ea5b-4deb-958c-51227dbae0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link gh-submenu-item gh-tickets-option</value>
      <webElementGuid>a574d4ad-b20d-40f9-9383-96cdbca7e961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/articles/all</value>
      <webElementGuid>2fb9d1a8-6f44-47a4-8a65-f9c22449026e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/UI/articles/all</value>
      <webElementGuid>69602381-d417-4319-97a3-612744a547f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Articles </value>
      <webElementGuid>cf8c2e0f-4b4e-47b7-98b9-0fd0c249ecf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/div[@class=&quot;row gh-100-width&quot;]/ul[@class=&quot;navbar-nav bd-navbar-nav flex-row&quot;]/li[@class=&quot;dropdown show&quot;]/ul[@class=&quot;dropdown dropdown-menu gh-kb-dropdown text-center show&quot;]/li[2]/a[@class=&quot;btn btn-link gh-submenu-item gh-tickets-option&quot;]</value>
      <webElementGuid>912dee06-4cb0-4eab-82dc-c9bcbc31e95b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ul/li[4]/ul/li[2]/a</value>
      <webElementGuid>fdad782a-7550-4597-82ba-6dd0ce425296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'All Articles')]</value>
      <webElementGuid>9dcc449d-968a-4722-8941-de3d51c897ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Articles'])[1]/following::a[1]</value>
      <webElementGuid>32ad8d7a-77b5-425b-a03c-26a44e906564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Knowledge Base'])[1]/following::a[2]</value>
      <webElementGuid>b068d83c-9535-419d-8b46-37ca432d3a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analytics'])[1]/preceding::a[1]</value>
      <webElementGuid>ae364301-8d88-40f5-89b3-381774affdb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Articles']/parent::*</value>
      <webElementGuid>9276b930-5acd-4453-8377-640b220be730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/UI/articles/all')]</value>
      <webElementGuid>84ad23d4-7a8a-4f5d-8cf4-949ad88d9f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/a</value>
      <webElementGuid>f6cfcdf7-a043-4b5b-bbaa-d91899e11f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/UI/articles/all' and (text() = 'All Articles ' or . = 'All Articles ')]</value>
      <webElementGuid>86f2c88a-c81c-4084-a4df-08e532ad8700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
