<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All Users</name>
   <tag></tag>
   <elementGuidId>01eff536-7864-449e-9cd7-a97c69914007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='allUsersLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#allUsersLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>230e7708-69cc-49c2-afd9-3a462a9a74c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-dropdown-hidden-link col-xl-12</value>
      <webElementGuid>e06b4842-6664-45f2-843f-3017b3f364ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>allUsersLink</value>
      <webElementGuid>eb429dac-ddcf-4dc3-9bc7-fcbe1c404117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/users/all</value>
      <webElementGuid>2d0be60d-8572-4a3c-8abf-f7d099a7f9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/UI/users/all</value>
      <webElementGuid>55ca9d40-99e7-4530-8662-1c71169ee26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> All Users </value>
      <webElementGuid>13508712-2bbd-41aa-b981-4352f7abd49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allUsersLink&quot;)</value>
      <webElementGuid>fb73a2e0-6670-4f87-8817-0e2ed9c4ade6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='allUsersLink']</value>
      <webElementGuid>bde2ea33-60e3-4c4f-a637-37ed6a9b3d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='k-menu13-child0']/li/div/a</value>
      <webElementGuid>73a2719f-61b7-46fc-a486-787a657c7cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'All Users')]</value>
      <webElementGuid>483b36cd-1d37-4afa-a6d2-c25cdedb2a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'allUsersLink', '&quot;', ')')])[1]/following::a[1]</value>
      <webElementGuid>2684c520-2986-4ec8-8abc-f98f09c4dda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::a[1]</value>
      <webElementGuid>50448178-a5fd-40ce-acf2-66568ed26376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles'])[1]/preceding::a[1]</value>
      <webElementGuid>e5a95711-c607-4029-9753-2287debfa6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Groups'])[1]/preceding::a[2]</value>
      <webElementGuid>1b1ef43a-b657-4d6a-9b96-880ac3705557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Users']/parent::*</value>
      <webElementGuid>04ee2a05-7ee2-4712-b7bf-2dda177637db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/UI/users/all')]</value>
      <webElementGuid>ffec587f-10c0-47c5-96b5-d0ce907569ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/div/a</value>
      <webElementGuid>62160f14-09ee-4a51-b384-1e4d4f679262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'allUsersLink' and @href = '/UI/users/all' and (text() = ' All Users ' or . = ' All Users ')]</value>
      <webElementGuid>7ad56d8b-7446-4311-8bcf-8f8c74af6d1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
