<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Roles</name>
   <tag></tag>
   <elementGuidId>bbb83d08-0d0c-445b-bc87-7ce27c2c4510</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='rolesLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rolesLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1e147ff6-69c8-4c17-8fdc-fb3cd62ed327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-dropdown-hidden-link col-xl-12</value>
      <webElementGuid>2f040bee-c5e9-4623-8d7a-372e97359e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rolesLink</value>
      <webElementGuid>be5533ac-57d4-4d7f-8ab9-be91d1dfbca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/roles</value>
      <webElementGuid>2e1f1756-937b-438e-b6a0-7c1ef46945f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/UI/roles</value>
      <webElementGuid>a84d7d9d-4f87-4205-b3c1-1f8a567dd710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Roles </value>
      <webElementGuid>3388b10e-874a-4629-a19e-886b7449841b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rolesLink&quot;)</value>
      <webElementGuid>d7c0f95c-54d1-4b1e-a7f6-e5b959c51cfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='rolesLink']</value>
      <webElementGuid>6ba6bfb3-d22f-483e-b25b-71fad319338d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='k-menu13-child0']/li[2]/div/a</value>
      <webElementGuid>f9a829fc-4f8f-4f8f-ab40-09cf44144a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Roles')]</value>
      <webElementGuid>1eca4e65-0d6b-4e6e-a6be-80d9ecd9941d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Users'])[1]/following::a[1]</value>
      <webElementGuid>8463bdca-4834-41d5-a26c-e24824ea4f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'rolesLink', '&quot;', ')')])[1]/following::a[2]</value>
      <webElementGuid>b530f6f6-e644-42d4-af29-537d993a8d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Groups'])[1]/preceding::a[1]</value>
      <webElementGuid>f1ca19af-a1e6-4dce-ab7b-47d611b8b881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unattended Accounts'])[1]/preceding::a[2]</value>
      <webElementGuid>9ea7136e-b1ea-4b3c-bf65-3541a2c971d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Roles']/parent::*</value>
      <webElementGuid>636e6962-9989-4fad-a5fd-afc7d16f5cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/UI/roles')]</value>
      <webElementGuid>324397fa-c23a-4cfd-9865-38cd8c978cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a</value>
      <webElementGuid>b99731db-36aa-4b97-90b8-6ecf2b169909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rolesLink' and @href = '/UI/roles' and (text() = ' Roles ' or . = ' Roles ')]</value>
      <webElementGuid>52d21a94-332c-449b-8520-fb3123cf1690</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
