<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Service Groups</name>
   <tag></tag>
   <elementGuidId>4da72af9-bde8-4d4a-96d4-f00df59343a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='serviceGroupsLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#serviceGroupsLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2cd8d3ec-b277-4185-8a8d-d259673425e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-dropdown-hidden-link col-xl-12</value>
      <webElementGuid>24ea28d0-e5ff-40a5-aaec-11fb7ca3cbec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serviceGroupsLink</value>
      <webElementGuid>a4c1c694-1eaa-43c1-99e0-4095487a52f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/service-groups</value>
      <webElementGuid>fe8a4eb9-9a52-4fb9-a9a8-32722c62f4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/UI/service-groups</value>
      <webElementGuid>1832480a-0360-49f7-8eed-398d5994e744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Service Groups </value>
      <webElementGuid>add1d36e-5395-457c-9571-8b525b7f4e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serviceGroupsLink&quot;)</value>
      <webElementGuid>1f0cbac0-7963-4e07-9871-2d8da2ea3bec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='serviceGroupsLink']</value>
      <webElementGuid>c8a4a07b-608f-4281-bc10-bb1b852d6f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='k-menu13-child0']/li[3]/div/a</value>
      <webElementGuid>8eab6fc1-2a22-4039-8025-1a19930a9625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Service Groups')]</value>
      <webElementGuid>9e442585-7de4-475f-8132-a122f8a2e783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles'])[1]/following::a[1]</value>
      <webElementGuid>c480c6d1-0fc7-458f-81fa-9ae50f3f6432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Users'])[1]/following::a[2]</value>
      <webElementGuid>6321c5ad-ddf0-48ab-88a1-0e93766ca9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unattended Accounts'])[1]/preceding::a[1]</value>
      <webElementGuid>70728bb3-284b-4e0b-a7d6-79ac1d8849c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Service Groups']/parent::*</value>
      <webElementGuid>ca63baeb-1883-4b13-8956-d5c5d011eb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/UI/service-groups')]</value>
      <webElementGuid>549cccef-8ffd-435e-9816-82ca5d934643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a</value>
      <webElementGuid>93694835-bafc-4dd4-82da-271622008d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'serviceGroupsLink' and @href = '/UI/service-groups' and (text() = ' Service Groups ' or . = ' Service Groups ')]</value>
      <webElementGuid>6b6b78c1-3951-4b07-a50b-1f78e0c65e3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
