<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Unattended Accounts</name>
   <tag></tag>
   <elementGuidId>30424a11-f17f-41d9-bcb0-979d9ae81e47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='unattendedUsersLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#unattendedUsersLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>99449462-acc7-4437-8ecb-c9a4250318a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-dropdown-hidden-link col-xl-12</value>
      <webElementGuid>77ced156-a839-47d6-89f4-71a74292f430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unattendedUsersLink</value>
      <webElementGuid>92ae2ae0-932a-419b-bdf1-24df493a1b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/users/unattended</value>
      <webElementGuid>b91ce732-c91c-4541-8b1b-79f3ca0d0c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/UI/users/unattended</value>
      <webElementGuid>83312457-7ff3-419b-ab40-e386fa328869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Unattended Accounts </value>
      <webElementGuid>dcacd02e-1241-47d7-a54f-6565b72e7d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unattendedUsersLink&quot;)</value>
      <webElementGuid>7e7f83f6-44e3-4879-a51a-422b505d573b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='unattendedUsersLink']</value>
      <webElementGuid>22761496-7790-432f-9432-9e778eb804c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='k-menu13-child0']/li[4]/div/a</value>
      <webElementGuid>d94e757b-36b8-44fd-8554-b98d10e7ec72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Unattended Accounts')]</value>
      <webElementGuid>4915d43d-b7be-44c2-8e1d-84676a8ea081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Groups'])[1]/following::a[1]</value>
      <webElementGuid>d42c3d0e-dc0c-480e-810c-0b950c985eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles'])[1]/following::a[2]</value>
      <webElementGuid>4a9222c0-2cd8-497d-af73-9d1ddc442ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unattended Accounts']/parent::*</value>
      <webElementGuid>6da324c0-2f1c-436f-ae5d-05266899f412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/UI/users/unattended')]</value>
      <webElementGuid>6e334493-155e-4a19-a3fd-2189ae9a9f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/a</value>
      <webElementGuid>3f19d806-7da8-4b5f-8f80-a2444a4f2335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'unattendedUsersLink' and @href = '/UI/users/unattended' and (text() = ' Unattended Accounts ' or . = ' Unattended Accounts ')]</value>
      <webElementGuid>f2373ed7-6355-4f22-b2d5-3f83afc316ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
