<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>POST ValidateLogin</name>
   <tag></tag>
   <elementGuidId>01b91ac2-0737-4780-b1b2-4ad60e73e5cb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;Key\&quot;: \&quot;${TIPWebAPI_Key}\&quot;,\r\n    \&quot;Phrase\&quot;: \&quot;${TIPWebAPI_Phrase}\&quot;\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>8d6a227c-fad0-4ac4-b610-e5737e46177a</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.5.2</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${TIPWebAPI_Url}api/Login/ValidateLogin</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.TIPWebAPI_Url</defaultValue>
      <description></description>
      <id>515371bf-6684-423d-93b6-de16e64873c9</id>
      <masked>false</masked>
      <name>TIPWebAPI_Url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.TIPWebAPI_Key</defaultValue>
      <description></description>
      <id>126e1cdc-c1cb-4931-88ea-30a36af22322</id>
      <masked>false</masked>
      <name>TIPWebAPI_Key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.TIPWebAPI_Phrase</defaultValue>
      <description></description>
      <id>1ff28857-f7fd-48ef-9a79-647085a58416</id>
      <masked>false</masked>
      <name>TIPWebAPI_Phrase</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
