<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Unassigned------------------  Addy M_541135</name>
   <tag></tag>
   <elementGuidId>fab1b2ec-8468-45b7-90d2-3e30acaec4fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-control.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='actionValues']/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>technician</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>technician</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unassigned------------------  Addy McAdmin  Admin Pari  Alex Lifeson  Alexander Aplin  Anna Maxin  Arthur Dent  Attronica Attronica  Balakrishnan Devi  Carlos Mora  CelineAdmin Suarez  CelineTech Suarez  Chase Admin  Chase Tech  Chaz Shuck  CTSI CTSI  Dakshi Kirthi  Dominique Noel  Ed Adshead  gcollazo@hayessoft.com   Geddy Lee  Guy Montag  Hiko Kuabara  James Bazan  Jariatu Kamara  Jason Admin  Jason Tech  Jason Tech2  Jennifer Cooper  John Crites  kirthi bala  kirthi Bala krishnan  Kiruthiga bala  Loan Le  Mericko Marlowe  Natlie Riley  Network Team  Renard fields  Rick Sanchez  Rocky Raccoon  Rudy Ordonez  Steph Delgado  subbarao Admin  subbarao technician  Tam Thai  Tech Pari  Tech1 Pari1  Test SA1  Thanh Le  Thon Thai  Tosh Horita  Tri Truong  unknown unknown  Uwadia Erumsele  William Kita  William Shakespeare </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionsContainer&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;card gh-cardstock&quot;]/div[@class=&quot;card flat-corner panel-default&quot;]/div[@class=&quot;card-body smaller-cards&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-12 gh-no-left-padding gh-no-right-padding&quot;]/div[@class=&quot;row gh-no-margin&quot;]/div[@class=&quot;col-xl-10&quot;]/div[@class=&quot;row&quot;]/div[@id=&quot;actionValues&quot;]/div[@class=&quot;row&quot;]/select[@class=&quot;form-control ng-untouched ng-pristine ng-valid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actionValues']/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign to:'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What action should be performed?'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign to Service Group:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Status To:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
