<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>POST CreateSLATarget</name>
   <tag></tag>
   <elementGuidId>db529825-1081-46eb-9623-9f4d6723a0ff</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n\t\&quot;slaNumber\&quot;: 1,\n\t\&quot;name\&quot;: \&quot;Default SLA Target\&quot;,\n\t\&quot;description\&quot;: \&quot;\&quot;,\n\t\&quot;enabled\&quot;: true,\n\t\&quot;order\&quot;: 1,\n\t\&quot;edited\&quot;: true,\n\t\&quot;calculating\&quot;: false,\n\t\&quot;createdByUserID\&quot;: 0,\n\t\&quot;lastModifiedByUserID\&quot;: 0,\n\t\&quot;slaTargetDetails\&quot;: [\n\t\t{\n\t\t\t\&quot;scheduleID\&quot;: 1,\n\t\t\t\&quot;targetValue\&quot;: 30,\n\t\t\t\&quot;targetTimeTypeID\&quot;: 1\n\t\t},\n\t\t{\n\t\t\t\&quot;scheduleID\&quot;: 1,\n\t\t\t\&quot;targetValue\&quot;: 1,\n\t\t\t\&quot;targetTimeTypeID\&quot;: 2\n\t\t}\n\t],\n\t\&quot;SLATargetRules\&quot;: [\n\t\t{\n\t\t\t\&quot;enabled\&quot;: true,\n\t\t\t\&quot;priorityID\&quot;: 1\n\t\t}\n\t]\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${HHD_API_Bearer}</value>
      <webElementGuid>388ffc76-2f4f-40fb-a2b3-76c6d82cf524</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>0c804842-4c0b-49ef-bd89-3e200364d332</webElementGuid>
   </httpHeaderProperties>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${HHD_API_Url}/api/SLATarget/CreateSLATarget</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.HHD_API_Url</defaultValue>
      <description></description>
      <id>f0b17431-8ea1-4244-9b48-6c79e28886f0</id>
      <masked>false</masked>
      <name>HHD_API_Url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.HHD_API_Bearer</defaultValue>
      <description></description>
      <id>4a9633ef-e954-4325-a109-e3c00f87e685</id>
      <masked>false</masked>
      <name>HHD_API_Bearer</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
