<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cost</name>
   <tag></tag>
   <elementGuidId>4500c01d-6a49-47f2-8e9d-6c915a3928b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>607a2903-7caa-4ac5-b467-f493b9ca4b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-ht-width ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>dd0f6637-7ee7-41b3-bd6d-22e53a744c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cost</value>
      <webElementGuid>ccbe44df-0793-4b5a-92ce-ca381fde0562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5aadffb7-d250-41e1-b96d-9f9a18ce7f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>37bd78a2-51ed-48fa-9dbf-714de35385ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>44a43bcd-19e3-4774-a72b-ead5f42f0893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>9d4c31af-149b-4f0d-8d39-de70a6788f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cost&quot;)</value>
      <webElementGuid>d8436e56-cc87-4bb6-99e3-14fef5ddf7da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cost']</value>
      <webElementGuid>6180eeb8-d7db-42cc-a675-3f1617596f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='partsMainGrid']/div/table/tbody/tr/td[7]/div/input</value>
      <webElementGuid>4ecb096f-f217-4bcf-a15c-fe37d5abbaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/input</value>
      <webElementGuid>2b928a58-01b5-4f8f-8233-59008b91999d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cost' and @placeholder = '0']</value>
      <webElementGuid>210958ed-9706-414b-93a6-432156355a5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
