<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MinimumStock</name>
   <tag></tag>
   <elementGuidId>b2fac7a6-8e8e-4ebc-b911-fa919ead1aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#minimumStock</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='minimumStock']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23243e9f-1884-47c8-bc71-2ff7d5511848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-ht-width ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c99a55ce-1b51-447e-864d-c5e889db4a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>minimumStock</value>
      <webElementGuid>7c2fd479-b5b0-494b-a357-3d60e4e6fbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b3b40dce-3e9b-4065-8eaf-a9d01b197303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e03ec00d-db62-4407-9ed1-1af60bfb6980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>5c368271-d1cc-4fdd-b369-9dea0f5917b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>3d65e49e-39a1-4a63-b580-c329149a3cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minimumStock&quot;)</value>
      <webElementGuid>c8cf6aaf-4538-4f71-a9b1-94f94be4c921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='minimumStock']</value>
      <webElementGuid>92889cf8-b332-4437-8a15-7af8a78c71a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='partsMainGrid']/div/table/tbody/tr/td[8]/div/input</value>
      <webElementGuid>98329d91-4e09-440c-8cf1-4f70db9242b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/input</value>
      <webElementGuid>43a288a1-50b9-4f70-ac0c-cf970ad9aba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'minimumStock' and @placeholder = '0']</value>
      <webElementGuid>038e67d1-9045-4c98-bb47-2ed686f72010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
