<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Part_Name</name>
   <tag></tag>
   <elementGuidId>31e26f91-7bfb-4a2c-83bd-fce9fa849ecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#partName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='partName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03f922b0-209c-4930-9b91-3fc6a09ec93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-ht-width ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d9c1d461-5267-49a0-b67d-af17a91522eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partName</value>
      <webElementGuid>1ddd332f-ce50-4c5b-baef-41f39e1982f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>9b703e4e-88e8-46eb-a6db-ab382e48f923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partName&quot;)</value>
      <webElementGuid>5482e9c3-8d74-46b1-8488-6a4b663f6dd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partName']</value>
      <webElementGuid>35c69503-bff2-4824-90c8-0b83373e5795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='partsMainGrid']/div/table/tbody/tr/td[3]/div/input</value>
      <webElementGuid>296b24a3-80ce-412e-9c3a-ce5cfd81ac6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/input</value>
      <webElementGuid>3841c3b3-4e35-4a26-9018-b93d4ef52dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'partName']</value>
      <webElementGuid>b947a49c-88db-461c-a0cc-1d0a16c31fd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
