<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Part_Number</name>
   <tag></tag>
   <elementGuidId>9967b074-e379-4446-9f3c-26cdd0ad7a5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#partNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4ada2f7-96cf-4603-999b-7fcf478275e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-ht-width ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>c139c87d-e326-4e59-a334-fdbee3e79787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partNumber</value>
      <webElementGuid>adb299bd-c630-4bc9-bfde-8bb739753a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>8e0528b9-afee-4151-9168-ba444b9f2c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partNumber&quot;)</value>
      <webElementGuid>b9c8fcbd-4dcb-4f33-a4d6-6ff7ed746dfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partNumber']</value>
      <webElementGuid>29d2dd51-8779-4a33-a8e4-7689fd5d22d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='partsMainGrid']/div/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>e1538c5b-ebc4-40bd-9cd9-db8fa1f18b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>26accd4f-78b3-4122-8ba4-59356eb72ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'partNumber']</value>
      <webElementGuid>83411763-2530-4fe8-889a-ca9c2714b7c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
