<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_RudyUser Ordonez</name>
   <tag></tag>
   <elementGuidId>1d32a3b2-4d1b-42e9-8cb3-fd2e9037dfa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>543f08c1-1a78-4cab-a909-2f8346ae9875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> RudyUser Ordonez  </value>
      <webElementGuid>ff9ac789-131b-45db-9ed0-cf30fbb8a4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/div[@class=&quot;row w-100&quot;]/div[@class=&quot;col-lg-2 gh-navbar-user-settings-dropdown-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 mobile-navbar-item gh-no-padding-right&quot;]/ul[@class=&quot;gh-no-padding-left&quot;]/li[@class=&quot;dropdown&quot;]/a[@class=&quot;dropdown-toggle btn btn-link&quot;]/b[1]</value>
      <webElementGuid>d4c1f9b2-81e4-44ce-840e-75c451af3408</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/div[3]/div/div/ul/li/a/b</value>
      <webElementGuid>76c466fe-cf82-4d9b-971a-4815556a4591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sandbox from Hayes Software'])[1]/following::b[1]</value>
      <webElementGuid>933fc346-8fd8-4f75-879b-be341350e45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Knowledge Base'])[1]/following::b[1]</value>
      <webElementGuid>0deb6090-24dc-4086-82b5-ec4a762985cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Settings'])[1]/preceding::b[1]</value>
      <webElementGuid>d50d2a04-9480-4181-aa28-b77bf4614850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::b[1]</value>
      <webElementGuid>ff081d9c-9d2e-449d-b496-f72f7daf69d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>6820a8b8-4ea0-4184-aed4-f27c6f8d5de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = ' RudyUser Ordonez  ' or . = ' RudyUser Ordonez  ')]</value>
      <webElementGuid>42d249b8-8a0d-4e48-8ae1-7f9697b5e462</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
