<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>New Postman Request(2)</name>
   <tag></tag>
   <elementGuidId>4863a040-503d-4b4e-afa4-643fc0ec712c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;[\r\n    {\r\n        \&quot;ProductNumber\&quot;: 0, \r\n        \&quot;ProductName\&quot;: \&quot;20 UNIT NOTEBOOK STORAGE CART\&quot;,\r\n        \&quot;ProductDescription\&quot;: \&quot;20 UNIT NOTEBOOK STORAGE CART\&quot;,\r\n        \&quot;ProductType\&quot;: \&quot;Unspecified\&quot;,\r\n        \&quot;Model\&quot;: \&quot;None\&quot;,\r\n        \&quot;Manufacturer\&quot;: \&quot;None\&quot;,\r\n        \&quot;SuggestedPrice\&quot;: 1064.00,\r\n        \&quot;Notes\&quot;: \&quot;Hayes Integration 05/21/2018\&quot;,\r\n        \&quot;SKU\&quot;: \&quot;\&quot;,\r\n        \&quot;ProjectedLife\&quot;: 0,\r\n        \&quot;CustomField1\&quot;: null,\r\n        \&quot;CustomField2\&quot;: null,\r\n        \&quot;CustomField3\&quot;: null\r\n    }\r\n]&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>7a73923f-cc6c-4505-ad9e-b54a15610fbf</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${TIPWebAPI_Bearer}</value>
      <webElementGuid>19bbfd62-4888-4b69-ad47-6924a736c222</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.6.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${TIPWebAPI_Url}/api/Integrations/Products/UpsertProducts</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.TIPWebAPI_Url</defaultValue>
      <description></description>
      <id>dc2d7d05-da49-4a58-b1f4-e3c1a9eb24de</id>
      <masked>false</masked>
      <name>TIPWebAPI_Url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.TIPWebAPI_Bearer</defaultValue>
      <description></description>
      <id>6a60b34e-165f-4c7a-a45a-d18fa2d73731</id>
      <masked>false</masked>
      <name>TIPWebAPI_Bearer</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
