<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>New Postman Request(6)</name>
   <tag></tag>
   <elementGuidId>34f87046-40d0-4300-bcf0-9d136f54b8a4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;[\r\n    {\r\n        \&quot;vendorID\&quot;: 0,\r\n        \&quot;vendorName\&quot;: \&quot;PRECISION PLUMBERS CO\&quot;,\r\n        \&quot;contact\&quot;: \&quot;\&quot;,\r\n        \&quot;address1\&quot;: \&quot;\&quot;,\r\n        \&quot;address2\&quot;: \&quot;\&quot;,\r\n        \&quot;city\&quot;: \&quot;\&quot;,\r\n        \&quot;state\&quot;: \&quot;\&quot;,\r\n        \&quot;zipCode\&quot;: \&quot;\&quot;,\r\n        \&quot;phone\&quot;: \&quot;\&quot;,\r\n        \&quot;fax\&quot;: \&quot;\&quot;,\r\n        \&quot;email\&quot;: \&quot;\&quot;,\r\n        \&quot;accountNumber\&quot;: \&quot;96452\&quot;,\r\n        \&quot;Notes\&quot;: \&quot;Bla bla bla\&quot;\r\n    }\r\n]&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>c01fac9a-3210-4176-a359-a351cfc792c0</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${TIPWebAPI_Bearer}</value>
      <webElementGuid>dbd8f807-5eb7-417c-b057-e04e017a6cf9</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.6.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${TIPWebAPI_Url}/api/Integrations/Vendors/AddVendors</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.TIPWebAPI_Url</defaultValue>
      <description></description>
      <id>946b34e3-9571-4286-b002-27f7dbd107e1</id>
      <masked>false</masked>
      <name>TIPWebAPI_Url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.TIPWebAPI_Bearer</defaultValue>
      <description></description>
      <id>b1f7eb7b-d1d9-4a28-ab42-998d3bdbe5b5</id>
      <masked>false</masked>
      <name>TIPWebAPI_Bearer</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
