<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Assign to Service Group_k-12c421cf-23_bb1726</name>
   <tag></tag>
   <elementGuidId>2cbfd63f-c4aa-428d-82f9-ba78777c7be0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#k-12c421cf-2376-420a-8947-6fd967c7a739</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='serviceGroupList']/div/div/div/kendo-multiselect/div/kendo-searchbar/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;k-12c421cf-2376-420a-8947-6fd967c7a739&quot;)[count(. | //input[@autocomplete = 'off' and @size = '32' and @id = 'k-12c421cf-2376-420a-8947-6fd967c7a739' and @placeholder = 'Click to Select Service Group(s)' and @class = 'k-input' and @tabindex = '0' and @dir = 'ltr' and @role = 'listbox' and @aria-disabled = 'false' and @aria-readonly = 'false' and @aria-haspopup = 'true' and @aria-expanded = 'true' and @aria-describedby = '9a946ebc-c353-4b11-850e-e483fb7ced29']) = count(//input[@autocomplete = 'off' and @size = '32' and @id = 'k-12c421cf-2376-420a-8947-6fd967c7a739' and @placeholder = 'Click to Select Service Group(s)' and @class = 'k-input' and @tabindex = '0' and @dir = 'ltr' and @role = 'listbox' and @aria-disabled = 'false' and @aria-readonly = 'false' and @aria-haspopup = 'true' and @aria-expanded = 'true' and @aria-describedby = '9a946ebc-c353-4b11-850e-e483fb7ced29'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-12c421cf-2376-420a-8947-6fd967c7a739</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Click to Select Service Group(s)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>9a946ebc-c353-4b11-850e-e483fb7ced29</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-12c421cf-2376-420a-8947-6fd967c7a739&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-12c421cf-2376-420a-8947-6fd967c7a739']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='serviceGroupList']/div/div/div/kendo-multiselect/div/kendo-searchbar/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/kendo-multiselect/div/kendo-searchbar/input</value>
   </webElementXpaths>
</WebElementEntity>
