<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All Fields</name>
   <tag></tag>
   <elementGuidId>1701ca6f-a08b-4f6a-8fed-d636274cf9be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='allFieldsLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#allFieldsLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0c6794c-d21a-4d72-afbb-cb8d77fa2179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-dropdown-hidden-link col-xl-12</value>
      <webElementGuid>ecfedbce-2ee9-441f-96bb-898b9171ad8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testing</name>
      <type>Main</type>
      <value>All Fields</value>
      <webElementGuid>b9cbd71f-d13c-4eca-9e4d-de84834ecf2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>allFieldsLink</value>
      <webElementGuid>4d20f846-37bc-440a-a124-98c699f380e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/fields</value>
      <webElementGuid>37c8e088-ce75-4a20-9d15-e9eb28decb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/UI/fields</value>
      <webElementGuid>b65e864f-8784-4927-866e-5a1d824549c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> All Fields </value>
      <webElementGuid>35ff65e2-2d2b-4b5f-9551-29c83eec6a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allFieldsLink&quot;)</value>
      <webElementGuid>6d7291d0-f192-4bf0-b140-1fe72ef92adf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='allFieldsLink']</value>
      <webElementGuid>9cacfaa4-7bf3-4b91-8e10-b1b6275c12ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='k-menu1-child0']/li/div/a</value>
      <webElementGuid>4cee3916-8a1b-474e-8e83-89092317789c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'All Fields')]</value>
      <webElementGuid>83c8ed06-7118-4f84-ada5-ce15f985544b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'allFieldsLink', '&quot;', ')')])[1]/following::a[1]</value>
      <webElementGuid>9849c336-9aac-4baa-ada8-b8682829948a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::a[1]</value>
      <webElementGuid>e234911a-725e-4b48-8ef7-2ecd5f169f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priorities'])[1]/preceding::a[1]</value>
      <webElementGuid>def2dcb5-b559-4640-a4ab-ac2ae69598f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Problem Types'])[1]/preceding::a[2]</value>
      <webElementGuid>464b540c-eeec-4608-85ad-91b6e6fb51bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Fields']/parent::*</value>
      <webElementGuid>2510edde-9527-49a6-a423-b60d19420ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/UI/fields')]</value>
      <webElementGuid>62f55f44-57c3-454a-a72a-18ceba2c14d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/div/a</value>
      <webElementGuid>5fd0151b-bbe0-4c43-b413-ed10583c303b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'allFieldsLink' and @href = '/UI/fields' and (text() = ' All Fields ' or . = ' All Fields ')]</value>
      <webElementGuid>b17ac920-a55e-4748-8762-3ad911e31ca2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
