<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Priorities</name>
   <tag></tag>
   <elementGuidId>07a90867-9b22-40c8-a7ea-27a7123128bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='prioritiesLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prioritiesLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>781b2ed0-d9cf-4e70-84f5-6c2c9fe4e731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-dropdown-hidden-link col-xl-12</value>
      <webElementGuid>146682c4-5ce6-4cf6-bf1d-497d0dbba612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testing</name>
      <type>Main</type>
      <value>Priorities</value>
      <webElementGuid>59c897ce-096a-49b1-9664-0fa4375f4fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prioritiesLink</value>
      <webElementGuid>3081a4b5-99f6-48a9-9610-49acaeafeb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/ticket-priorities</value>
      <webElementGuid>b6b5b76f-cad4-4e82-8f6e-5635fe28680a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/UI/ticket-priorities</value>
      <webElementGuid>f7b400b5-61d8-46c6-99cb-1f7a561050d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Priorities </value>
      <webElementGuid>dc2246d3-24fb-417a-b0f0-088feec6ebe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prioritiesLink&quot;)</value>
      <webElementGuid>14228567-1b8d-40d3-b094-faf3da9417ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='prioritiesLink']</value>
      <webElementGuid>0a82ba26-fe4c-46bf-92e1-4f9e0d835319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='k-menu1-child0']/li[2]/div/a</value>
      <webElementGuid>7e73e709-b05a-4725-ba71-73b5583ed0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Priorities')]</value>
      <webElementGuid>8b2a40b6-d15a-4724-b8fd-84ca2b5d6166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Fields'])[1]/following::a[1]</value>
      <webElementGuid>311605ff-31a9-4618-869b-0b1731f5ebab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'prioritiesLink', '&quot;', ')')])[1]/following::a[2]</value>
      <webElementGuid>c6933ae5-67b2-4bc5-82fc-5be91d4e8338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Problem Types'])[1]/preceding::a[1]</value>
      <webElementGuid>dd811296-12f0-428a-ab21-7b1469d53666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticket Templates'])[1]/preceding::a[2]</value>
      <webElementGuid>82219312-b5aa-4c45-a840-30fe3474292d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Priorities']/parent::*</value>
      <webElementGuid>16fb8ab5-dc5a-4359-ba5b-6fb3ca71727e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/UI/ticket-priorities')]</value>
      <webElementGuid>f41fbddc-96f9-46ad-889f-aaedd5ac3e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a</value>
      <webElementGuid>5b3a33b4-d076-41d1-9d5d-f124c568233c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'prioritiesLink' and @href = '/UI/ticket-priorities' and (text() = ' Priorities ' or . = ' Priorities ')]</value>
      <webElementGuid>9a4b5538-47f5-4b18-a382-701009b173a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
