<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Problem Types</name>
   <tag></tag>
   <elementGuidId>4d7b8bc7-86cf-4f01-a668-e3a6094071d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='problemTypesLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#problemTypesLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2df027ad-72a1-44a9-9518-96e1f2e95a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-dropdown-hidden-link col-xl-12</value>
      <webElementGuid>fa4427c4-1c85-48d4-a62b-0be2b1b0ac5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testing</name>
      <type>Main</type>
      <value>Problem Types</value>
      <webElementGuid>ece39983-7b43-430b-ab2a-1d7774ccba42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>problemTypesLink</value>
      <webElementGuid>b1a72e1e-d909-4cd1-aa0f-8878c104e547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/problem-types</value>
      <webElementGuid>ffef5614-a733-4d13-8e8d-e4f6cbf74f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/UI/problem-types</value>
      <webElementGuid>83977222-fa10-40ca-a7ab-e109efe0611d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Problem Types </value>
      <webElementGuid>58c0da35-28c9-4d95-a9f4-aea667d37ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;problemTypesLink&quot;)</value>
      <webElementGuid>8ac56038-5138-4b9e-8b32-8a7e436640fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='problemTypesLink']</value>
      <webElementGuid>40ae409d-d57a-4f7d-a155-7d3ed4c01e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='k-menu1-child0']/li[3]/div/a</value>
      <webElementGuid>908362b6-6a77-4dc5-8789-df8837f495dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Problem Types')]</value>
      <webElementGuid>143466ee-366c-4c99-818d-83abd3073277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priorities'])[1]/following::a[1]</value>
      <webElementGuid>e86f28cf-ea48-49c6-a7e7-88be7362e027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Fields'])[1]/following::a[2]</value>
      <webElementGuid>91c05bd9-a90d-4d28-8c71-2c4c1c60f02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticket Templates'])[1]/preceding::a[1]</value>
      <webElementGuid>e82aa6be-2e48-4918-9dd4-d8568e6ece71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Problem Types']/parent::*</value>
      <webElementGuid>83f4252d-042b-4979-8326-de762486bdbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/UI/problem-types')]</value>
      <webElementGuid>359e2969-40bb-424d-bdd6-43ed76186a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a</value>
      <webElementGuid>2d643bf6-d2c8-4805-87b6-30be6df4a3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'problemTypesLink' and @href = '/UI/problem-types' and (text() = ' Problem Types ' or . = ' Problem Types ')]</value>
      <webElementGuid>437a00df-8bf8-4ec5-81ef-0731df9831e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
