<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ticket Templates</name>
   <tag></tag>
   <elementGuidId>316faf53-0f93-4d50-9759-6e72dfbc2bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ticketTemplatesLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ticketTemplatesLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c52ce32-8f4f-42ed-8406-64d747b91a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-dropdown-hidden-link col-xl-12</value>
      <webElementGuid>f6eec42d-064a-4863-87d9-1dfe8e7d3fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testing</name>
      <type>Main</type>
      <value>Ticket Templates</value>
      <webElementGuid>9a4f166c-3e2d-4f24-8569-139195d952e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ticketTemplatesLink</value>
      <webElementGuid>1096bb88-7a8c-4e88-b14f-12deb438de68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/ticket-templates</value>
      <webElementGuid>dd4c3124-e87b-492a-a15d-62e4f717dea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/UI/ticket-templates</value>
      <webElementGuid>7f55d2c1-f456-4422-a87c-0e7b4a6f9e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ticket Templates </value>
      <webElementGuid>f224b63d-7717-4c2f-aff9-fe664883b26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ticketTemplatesLink&quot;)</value>
      <webElementGuid>3926ae33-95ef-4c44-9a6d-8197427f3a04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ticketTemplatesLink']</value>
      <webElementGuid>5d5b1ec2-92af-4567-8326-4bd70b66a4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='k-menu1-child0']/li[4]/div/a</value>
      <webElementGuid>2f0cf6f0-3ed3-4e86-bb0c-c40e5e4f783a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ticket Templates')]</value>
      <webElementGuid>2be4f9ff-1b20-454b-8329-4ce962ff6587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Problem Types'])[1]/following::a[1]</value>
      <webElementGuid>9d03c49b-c807-4a96-8013-5da308d906e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priorities'])[1]/following::a[2]</value>
      <webElementGuid>53dd6c08-c64f-4f31-a24b-0ebd9cdf7d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ticket Templates']/parent::*</value>
      <webElementGuid>42c716bc-0704-4b08-8963-65ae1cab3a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/UI/ticket-templates')]</value>
      <webElementGuid>5b21b461-b238-4493-aabb-63fd87e06a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/a</value>
      <webElementGuid>1835570a-5c48-4cd6-81a6-5808d35df2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ticketTemplatesLink' and @href = '/UI/ticket-templates' and (text() = ' Ticket Templates ' or . = ' Ticket Templates ')]</value>
      <webElementGuid>2c5ca15c-1d63-4fc0-ae30-02e13f07cbbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
