<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Adobe Acrobat - Sw_img-fluid</name>
   <tag></tag>
   <elementGuidId>0baa2ce8-30d9-4c7d-be2c-cabb94a3e742</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://s3.amazonaws.com/staging-gethelp-files/Images/Seal_of_Approval.jpg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s3.amazonaws.com/staging-gethelp-files/Images/Seal_of_Approval.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;ng-tns-0-0&quot;]/app-root[1]/div[@class=&quot;row gh-body gh-no-margin&quot;]/div[@class=&quot;col-sm-12 gh-body-container&quot;]/block-ui[1]/div[@class=&quot;block-container&quot;]/div[@class=&quot;content fullWidth delay minDuration&quot;]/div[@class=&quot;tab-panel&quot;]/create-ticket[1]/div[@class=&quot;col-lg-12 gh-create-ticket-container&quot;]/div[@class=&quot;gh-create-ticket-content&quot;]/spinner-overlay[1]/div[@class=&quot;spinner-container&quot;]/div[@class=&quot;content fullWidth delay minDuration&quot;]/div[1]/wizard-component[1]/div[@class=&quot;content wizard&quot;]/div[@class=&quot;row no-margin wizard-content-wrapper&quot;]/select-problem-type-component[1]/div[@class=&quot;wizard-step&quot;]/div[@class=&quot;centered-content bottom-separation&quot;]/div[@class=&quot;row gh-problem-type-row-container&quot;]/div[@class=&quot;col-xl-12 gh-problem-types-desktop&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;row&quot;]/div[@id=&quot;problemTypesListAll&quot;]/problem-type-card[1]/div[@class=&quot;card gh-no-box-shadow gh-problem-type-card-top-margin-only gh-desktop-problem-type-card&quot;]/div[@class=&quot;card gh-flat-corner panel-default gh-no-margin&quot;]/div[@class=&quot;card-body row gh-problem-type-card-padding&quot;]/div[@class=&quot;col-sm-12 gh-flat-corner gh-no-padding&quot;]/section[@class=&quot;image gh-no-padding&quot;]/img[@class=&quot;img-fluid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='problemTypesListAll']/problem-type-card/div/div/div/div/section/img)[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://s3.amazonaws.com/staging-gethelp-files/Images/Seal_of_Approval.jpg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/problem-type-card/div/div/div/div/section/img</value>
   </webElementXpaths>
</WebElementEntity>
