<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dashboard</name>
   <tag></tag>
   <elementGuidId>cc8e6919-df8b-4880-a6d7-3cee06a90d1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dashboardBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dashboardBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6af30a4-9185-4546-a712-fd29c0e43ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn gh-dashboard-navbar-button</value>
      <webElementGuid>8e03e9ed-903f-4183-86d4-c5cb0b5dde88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dashboardBtn</value>
      <webElementGuid>b8e26939-2350-4537-b1bf-95a4235b8074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>9401eabb-f63b-48b0-ae9c-b57e9c074cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboardBtn&quot;)</value>
      <webElementGuid>78ff253f-aa0b-40f5-ad88-9f1596568d1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dashboardBtn']</value>
      <webElementGuid>0b069a0a-8966-4d48-840e-2500fe96af49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ul/li/button</value>
      <webElementGuid>b1e5e790-1ff5-401f-8972-1a4ddae76323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tickets'])[1]/preceding::button[1]</value>
      <webElementGuid>ffdda861-18e4-427b-9c70-07e61d50ab81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Tickets'])[1]/preceding::button[1]</value>
      <webElementGuid>9a0dec02-7cee-4b8c-990d-7f3baef7b236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard']/parent::*</value>
      <webElementGuid>1dc65e16-cc6b-4f46-9a48-b9c2bcbc193c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>0c69072e-e3d8-4259-8973-ed11c25e451b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'dashboardBtn' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>38eba488-8532-4115-b581-771be55597f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
