<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Knowledge Base</name>
   <tag></tag>
   <elementGuidId>e460a066-202e-4da3-8a42-7c71eba6edc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.gh-blue-button.col-lg-3.col-xl-4.offset-xl-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76ad2477-9a44-495a-81ef-601233613455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn gh-blue-button col-lg-3 col-xl-4 offset-xl-0</value>
      <webElementGuid>fc95e345-c17c-400a-bdf0-13ba3de299c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d4a1a92-4bd3-4730-9067-9dc6df6d9cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link-active</name>
      <type>Main</type>
      <value>link-active</value>
      <webElementGuid>23ebd145-0c07-4bcb-8557-bbabf8a962b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Knowledge Base </value>
      <webElementGuid>ee473432-dd39-4a53-8913-ecfc64b81d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/div[@class=&quot;row w-100&quot;]/div[@class=&quot;col-lg-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 mobile-navbar-item&quot;]/div[@class=&quot;row&quot;]/button[@class=&quot;btn gh-blue-button col-lg-3 col-xl-4 offset-xl-0&quot;]</value>
      <webElementGuid>2205d7c9-52b6-4322-8a0d-2eaecab5b61d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>fb3681fa-a5cd-4885-8788-e3e2b10c60ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/div/div/div/div/button[3]</value>
      <webElementGuid>244a664b-1046-461c-9ca1-5c4d47b9478d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Ticket'])[1]/following::button[1]</value>
      <webElementGuid>b590b4d7-7005-4751-a744-38d85a6fb6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::button[2]</value>
      <webElementGuid>298756dc-526d-43fb-a3a8-95feb8577616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sandbox from Hayes Software'])[1]/preceding::button[1]</value>
      <webElementGuid>773d5d2b-958c-4589-9d69-ef9e77c8c75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Knowledge Base']/parent::*</value>
      <webElementGuid>5419b422-ac3f-45ab-ab15-612b487d5ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>15aa934b-a87a-4c5b-80be-fd526cffbd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Knowledge Base ' or . = ' Knowledge Base ')]</value>
      <webElementGuid>cfa0e662-ecec-4f62-bcc2-5d0ea913ffd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
