<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Show All TicketsShow Open TicketsShow Resolved TicketsShow Closed Tickets</name>
   <tag></tag>
   <elementGuidId>9877a0eb-a142-4c66-8717-aa7670bedd73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>73d73747-9770-4ac8-9bde-36535491b537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ea6f9423-b3b3-415e-a596-dbe1684810b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter</value>
      <webElementGuid>f9d26bec-4845-4e16-940f-b843890b547a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter</value>
      <webElementGuid>138aee0a-aa9a-4e19-a3c0-a6add6103e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>filter</value>
      <webElementGuid>578d978a-0063-42c1-a9c5-041dea1dfaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>5dc87b32-8029-488b-808e-47af4bccfa9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show All TicketsShow Open TicketsShow Resolved TicketsShow Closed Tickets</value>
      <webElementGuid>e4b76f24-2940-42a8-9d74-d37595fb3ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter&quot;)</value>
      <webElementGuid>309088f2-7d75-44a3-8d77-f6802ae4e3d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filter']</value>
      <webElementGuid>ea62d521-edf1-4333-9cd1-fb93a03564e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Tickets'])[1]/following::select[1]</value>
      <webElementGuid>fff96e52-8282-4454-ab64-f8432a4c7d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Ticket'])[2]/following::select[1]</value>
      <webElementGuid>683f1021-6455-4959-8cda-5847a9c52ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::select[1]</value>
      <webElementGuid>00ff0860-d468-40f5-9252-3075bd8e112c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolved'])[1]/preceding::select[1]</value>
      <webElementGuid>0fdcb71b-07c2-4826-907d-fdb822231357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>142d0968-cab3-4d62-a245-bb28ebd982f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filter' and @name = 'filter' and (text() = 'Show All TicketsShow Open TicketsShow Resolved TicketsShow Closed Tickets' or . = 'Show All TicketsShow Open TicketsShow Resolved TicketsShow Closed Tickets')]</value>
      <webElementGuid>f6d390d4-e42a-4fad-9bd0-11672858a234</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
