#false.
#@USER username to access database.
#@PASSWORD encrypted password.
#Mon Dec 18 14:58:59 CST 2023
URL=
CONNECTION_PROPERTIES={\n  "connectionProperty"\: [],\n  "props"\: {}\n}
SHOW_WARNING=false
DRIVERCLASSNAME=
SECURE_USER_ACCOUNT=false
USER=
PASSWORD=
