<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create Ticket</name>
   <tag></tag>
   <elementGuidId>dd00e606-28b7-4031-8d7a-7215243cc599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.gh-font-size-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24c69d32-becf-49d6-b7b3-10613dcfd246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-font-size-medium</value>
      <webElementGuid>de31de6b-139c-4c57-85ce-d9ef783da425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>5ca90544-0aea-42d9-be52-f8947bf558ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click To Add</value>
      <webElementGuid>012bce78-bac5-4a2e-8641-635fd66fa621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Create Ticket</value>
      <webElementGuid>05e6e758-2b13-44ad-b1cb-02c2126b2fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createTicketBtn&quot;)/a[@class=&quot;gh-font-size-medium&quot;]</value>
      <webElementGuid>177924ff-7f06-496c-9b84-9ad0b3fa94d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='createTicketBtn']/a</value>
      <webElementGuid>47a341da-0308-4ce0-bb34-cccf075e2c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create Ticket')]</value>
      <webElementGuid>a415b6b9-c873-4738-9959-32b44c3f2d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::a[1]</value>
      <webElementGuid>9ccd190c-7fae-4c20-aacc-8478ce2e34ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RO'])[1]/following::a[2]</value>
      <webElementGuid>628d470e-c86d-4da0-ba0a-efc2d97021c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[2]</value>
      <webElementGuid>dbb68603-dee6-49aa-b1ea-eab4182b6428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/a</value>
      <webElementGuid>46224362-d974-4191-b84a-6557a0d35968</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
