<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AUDIOVISUAL EQUIPMENT - DOCUMENT CAMERA</name>
   <tag></tag>
   <elementGuidId>3a591d90-3826-4513-8afa-017f502f7df4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[21]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#37a250fe-9650-4832-a63e-33dbcc4719dc-38</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>353ffe80-7e22-49fb-8526-b1a23d617786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>24925a19-5ddb-458c-87bf-e9065b3246b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5121a23e-2ce5-472e-8526-de60b6ae991f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>301784e0-3398-4cb6-a308-12198b86f0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>0b6a8195-089e-4091-aa18-a40eb8e86bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-index</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>67c76e6c-7625-4312-9eea-2c57d82a5e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-multiple-selection</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>142da322-dc0d-4ce5-97cb-b0f04d1ec735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>37a250fe-9650-4832-a63e-33dbcc4719dc-38</value>
      <webElementGuid>33095b5a-65e3-48c1-ad5c-e2a76bc38b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6230c2e6-6104-48df-95f0-3906b150040b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4ad4eb99-9bdb-4b76-8e6d-e98f7efeb702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUDIO/VISUAL EQUIPMENT - DOCUMENT CAMERA</value>
      <webElementGuid>f58bfcb7-d811-4e10-88bd-de1690e43aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;37a250fe-9650-4832-a63e-33dbcc4719dc-38&quot;)</value>
      <webElementGuid>09421ce2-9051-44fb-b972-eba26a5f5db9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='37a250fe-9650-4832-a63e-33dbcc4719dc-38']</value>
      <webElementGuid>df0ed520-af48-41cf-9158-1f9223daab48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='815fd1f2-cd9e-4d97-9d43-070b16f75829']/li[21]</value>
      <webElementGuid>d00f840e-d7b3-4a11-baa0-573000cef80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - CAMERA LENS'])[1]/following::li[1]</value>
      <webElementGuid>f7b0148e-3dfc-4420-ad0c-67f3b7f19195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - CAMERA'])[1]/following::li[2]</value>
      <webElementGuid>17c122a0-e39d-4736-b1bd-3711c3d36ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - FLAT SCREEN TV'])[1]/preceding::li[1]</value>
      <webElementGuid>a1701c8b-2505-446e-9588-3df4f3f48486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - GAMING SYSTEM'])[1]/preceding::li[2]</value>
      <webElementGuid>7fecf069-8e39-4350-89bf-78accd941799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AUDIO/VISUAL EQUIPMENT - DOCUMENT CAMERA']/parent::*</value>
      <webElementGuid>7ab0d1f1-26b5-4cf7-ad68-aa9e085c0ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[21]</value>
      <webElementGuid>4e9ded41-92be-4c0d-8287-72730da40431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '37a250fe-9650-4832-a63e-33dbcc4719dc-38' and (text() = 'AUDIO/VISUAL EQUIPMENT - DOCUMENT CAMERA' or . = 'AUDIO/VISUAL EQUIPMENT - DOCUMENT CAMERA')]</value>
      <webElementGuid>a451a8ce-be0b-4bc9-b84b-627efee3ad28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
