<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AUDIOVISUAL EQUIPMENT - OTHERS</name>
   <tag></tag>
   <elementGuidId>557f139e-2387-45cc-975f-0acea8a46310</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[26]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#27ead2c7-ed08-4533-8490-46e410d12954-40</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>76bc0ac4-499f-4987-95f2-7eced17d4174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>ed3d1261-5f7e-4b1a-9a83-1ed90880d679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>55c440b9-acb2-45ba-abe7-fb9f7e2ddd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>eed46895-1562-4e22-80dd-a09e3f21053f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>f5aa11cc-1f0a-49e8-beca-6403fb2d943c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-index</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>04b4c278-6533-4400-b274-8530cf9dfdee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-multiple-selection</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95eedfb0-11cd-4faa-9dd9-b7e7d5c182a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>27ead2c7-ed08-4533-8490-46e410d12954-40</value>
      <webElementGuid>afb7ffda-0a34-4467-aac3-ee5d47231be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>343b6a84-2d31-49c1-a633-d13fc31a73a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>18d99e9d-f5ce-4fb7-8ee4-3b27c6e2297d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUDIO/VISUAL EQUIPMENT - OTHERS</value>
      <webElementGuid>c1fffa75-2aa1-4e97-a408-e657f8cc3358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;27ead2c7-ed08-4533-8490-46e410d12954-40&quot;)</value>
      <webElementGuid>a1c7659c-7b69-4adb-b4a5-2b3be1c69149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='27ead2c7-ed08-4533-8490-46e410d12954-40']</value>
      <webElementGuid>215eec02-f8dd-4813-a2bc-94d2d80c8d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='7db24d01-d75c-481d-8c2d-410d9f610fa9']/li[26]</value>
      <webElementGuid>5b5927b5-531b-42c9-bbf9-37399c97092e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - INTERACTIVE WHITEBOARD'])[1]/following::li[1]</value>
      <webElementGuid>825347e0-3634-4797-8a9a-524adabcc79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - HEADPHONES'])[1]/following::li[2]</value>
      <webElementGuid>5bf204c6-7e19-438d-994a-c012565aaa59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - PROJECTORS'])[1]/preceding::li[1]</value>
      <webElementGuid>8cb9ad50-a590-4e56-b956-d93801f8bf72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - SOUND'])[1]/preceding::li[2]</value>
      <webElementGuid>080ceaad-762e-4dbe-968a-f62349800563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AUDIO/VISUAL EQUIPMENT - OTHERS']/parent::*</value>
      <webElementGuid>20657bcb-fa0a-44f3-ad68-da4a402a49b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[26]</value>
      <webElementGuid>ce94ba3e-1244-43ce-9c7f-09a5666c1e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '27ead2c7-ed08-4533-8490-46e410d12954-40' and (text() = 'AUDIO/VISUAL EQUIPMENT - OTHERS' or . = 'AUDIO/VISUAL EQUIPMENT - OTHERS')]</value>
      <webElementGuid>c2ccbf97-9927-460b-b8a2-06f8f9c55a4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
