<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AUDIOVISUAL EQUIPMENT - CAMERA LENS</name>
   <tag></tag>
   <elementGuidId>e25f29d1-9d9b-401b-bf1c-d86ab7e47fff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[20]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#37a250fe-9650-4832-a63e-33dbcc4719dc-153</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>10383b76-1377-4382-8baa-a8fda0f32801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>3b8bba0a-18ef-4770-8996-82a4d7d928d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f3668f84-d221-4d03-9e82-d7a67344fe13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>e444ed56-3704-47cf-88b4-d9dba3a60bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>9dc93f48-470d-484d-8e41-b205b2e07875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-index</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>8fba6a6d-bd55-4198-ac18-941360e1c255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-multiple-selection</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a9245f05-f38e-4607-a119-64c60edaed30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>37a250fe-9650-4832-a63e-33dbcc4719dc-153</value>
      <webElementGuid>ef6d3604-6157-4447-841b-7621f91f0f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>336b41ec-052d-4e62-a37f-6c42977395b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>b832fae5-c597-444e-8acf-059bf82c9a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUDIO/VISUAL EQUIPMENT - CAMERA LENS</value>
      <webElementGuid>ca9b1c9a-78bb-4836-ab1c-4518540b0c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;37a250fe-9650-4832-a63e-33dbcc4719dc-153&quot;)</value>
      <webElementGuid>bc5b16ca-74af-49ce-beab-4720d9b22046</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='37a250fe-9650-4832-a63e-33dbcc4719dc-153']</value>
      <webElementGuid>b1ac6291-fa8c-4555-949f-054837fc7233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='815fd1f2-cd9e-4d97-9d43-070b16f75829']/li[20]</value>
      <webElementGuid>bab0beea-78c9-4a09-b76a-65f566c8d918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - CAMERA'])[1]/following::li[1]</value>
      <webElementGuid>eeca1c8e-6419-4432-b25d-03d86ad1de2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATHLETIC EQUIPMENT - SCOREBOARD'])[1]/following::li[2]</value>
      <webElementGuid>8dedadd4-1cfa-413d-a8c5-abdde6c6a4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - DOCUMENT CAMERA'])[1]/preceding::li[1]</value>
      <webElementGuid>a772ac4f-deb2-4c76-8349-2f1dfa6f00ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - FLAT SCREEN TV'])[1]/preceding::li[2]</value>
      <webElementGuid>c920d4c6-c7a1-4731-99d3-9b330c7636d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AUDIO/VISUAL EQUIPMENT - CAMERA LENS']/parent::*</value>
      <webElementGuid>bffd466d-78ea-4a99-b02a-35746c531012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[20]</value>
      <webElementGuid>8a22eaa0-f3bd-482a-bc66-fa0d794d372e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '37a250fe-9650-4832-a63e-33dbcc4719dc-153' and (text() = 'AUDIO/VISUAL EQUIPMENT - CAMERA LENS' or . = 'AUDIO/VISUAL EQUIPMENT - CAMERA LENS')]</value>
      <webElementGuid>46619a48-244a-4d4f-be04-a1156728d978</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
