<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AUDIOVISUAL EQUIPMENT - SPEAKERS</name>
   <tag></tag>
   <elementGuidId>201db841-bd6f-4d10-a667-4d459d9f5e41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[29]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#37a250fe-9650-4832-a63e-33dbcc4719dc-42</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f70d694b-081b-433e-b53d-8e75b247f3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>48b13992-08f8-4693-950a-8aaa56c8e283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3af77546-8c1a-4bc1-9e4d-1fad68636a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>41b504bf-09f8-4120-abe2-867bce3c795c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>9671b0db-c767-40cc-9ed9-2e77d636b9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-index</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>3fa78c39-442b-4f6e-9166-17e9d6d9b82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-multiple-selection</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d1aac2f2-cb7f-48d4-ab44-b0c6549ada92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>37a250fe-9650-4832-a63e-33dbcc4719dc-42</value>
      <webElementGuid>aa453b5c-a34f-4ed4-9c39-ff7ef871287b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>04dedc4a-c848-4065-a61d-c124c186f2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>326f3752-b369-4c68-8aaa-a3712c01882d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUDIO/VISUAL EQUIPMENT - SPEAKERS</value>
      <webElementGuid>2f7d3f3a-9b51-4977-bfc0-18f1f72f1907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;37a250fe-9650-4832-a63e-33dbcc4719dc-42&quot;)</value>
      <webElementGuid>2825360b-b166-4a51-aa37-931ba24464d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='37a250fe-9650-4832-a63e-33dbcc4719dc-42']</value>
      <webElementGuid>57658772-7446-4bcd-b720-912aa71925a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='815fd1f2-cd9e-4d97-9d43-070b16f75829']/li[29]</value>
      <webElementGuid>19835c00-cd15-4466-a6d6-54846c3079e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - SOUND'])[1]/following::li[1]</value>
      <webElementGuid>15a782fa-4807-4b08-b438-bfdce29cde66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - PROJECTORS'])[1]/following::li[2]</value>
      <webElementGuid>f301d5bc-db1d-40fe-9ecc-a99d65c283f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - TABLE'])[1]/preceding::li[1]</value>
      <webElementGuid>20b9b89a-27c7-4eaf-81fd-23b538c04242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - TELESCOPE EQUIPMENT'])[1]/preceding::li[2]</value>
      <webElementGuid>6d9e8a00-b42e-48af-98bb-514f45b13a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AUDIO/VISUAL EQUIPMENT - SPEAKERS']/parent::*</value>
      <webElementGuid>32564218-4f37-495d-9b9f-cb8f6d78ed13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[29]</value>
      <webElementGuid>b76059a9-a895-4324-9c81-748e373201de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '37a250fe-9650-4832-a63e-33dbcc4719dc-42' and (text() = 'AUDIO/VISUAL EQUIPMENT - SPEAKERS' or . = 'AUDIO/VISUAL EQUIPMENT - SPEAKERS')]</value>
      <webElementGuid>776b1d20-d317-4a46-a8fc-0ff4535e1231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
