<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AUDIOVISUAL EQUIPMENT - FLAT SCREEN TV</name>
   <tag></tag>
   <elementGuidId>d395e428-a622-45b2-aa2b-d98f4064b843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[22]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#37a250fe-9650-4832-a63e-33dbcc4719dc-74</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>82929d4d-8c97-476b-b3ba-c6121058fe74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>98da997b-7e3a-4dae-b0b2-79f9e8dec3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a435cce7-a904-4eb6-b57c-0ebe24b1239e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>6475fbdd-aeb8-466f-98cb-551dd6910ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>3bbb085b-7624-46f4-a3d5-431924853f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-index</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>25925617-df96-4e53-99a2-fd1c3658f7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-multiple-selection</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1535189f-ea48-4c06-8e5d-b44508df99a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>37a250fe-9650-4832-a63e-33dbcc4719dc-74</value>
      <webElementGuid>2147d91e-29cb-4edf-ab22-60689e1bf792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6b38aaea-ef76-4262-9ab2-7071aed7d39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>4f6ea30e-bcc7-4537-a9fb-a792142521d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUDIO/VISUAL EQUIPMENT - FLAT SCREEN TV</value>
      <webElementGuid>6f8b489d-b422-4312-8953-7fadeb7ceed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;37a250fe-9650-4832-a63e-33dbcc4719dc-74&quot;)</value>
      <webElementGuid>e09c27bb-c01c-44b9-a24c-c6b24e5421f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='37a250fe-9650-4832-a63e-33dbcc4719dc-74']</value>
      <webElementGuid>14c90f4a-6959-40e3-8867-d755f9d7db59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='815fd1f2-cd9e-4d97-9d43-070b16f75829']/li[22]</value>
      <webElementGuid>72b08abb-d53d-4ea3-a38a-3c93d7f41d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - DOCUMENT CAMERA'])[1]/following::li[1]</value>
      <webElementGuid>a7fc38ec-a4f9-49c6-9a35-3d0228b86b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - CAMERA LENS'])[1]/following::li[2]</value>
      <webElementGuid>62bd4731-b739-4fd0-9f5f-d07a4d7b4b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - GAMING SYSTEM'])[1]/preceding::li[1]</value>
      <webElementGuid>b4b97029-4c0d-4233-a002-2d48839a398c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - HEADPHONES'])[1]/preceding::li[2]</value>
      <webElementGuid>1675be32-6642-4386-acf4-23c695710eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AUDIO/VISUAL EQUIPMENT - FLAT SCREEN TV']/parent::*</value>
      <webElementGuid>399a936b-36da-4e33-971c-545ab6097167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[22]</value>
      <webElementGuid>f7ac6344-ab04-4586-8529-483a05bf90f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '37a250fe-9650-4832-a63e-33dbcc4719dc-74' and (text() = 'AUDIO/VISUAL EQUIPMENT - FLAT SCREEN TV' or . = 'AUDIO/VISUAL EQUIPMENT - FLAT SCREEN TV')]</value>
      <webElementGuid>301a98a3-4ed6-4c7a-80c3-d576c702660d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
