<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AUDIOVISUAL EQUIPMENT - VIDEO PLAYER</name>
   <tag></tag>
   <elementGuidId>bcc20114-2c43-40f6-84be-cdc017d2c4e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[34]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#37a250fe-9650-4832-a63e-33dbcc4719dc-43</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f9b4977d-4e87-44af-bdfc-19919e0d56e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>f197264a-1684-496f-affc-4f167497e4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8ecac1bd-44c4-4a1c-8058-e3070bfb9e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>53ebf77c-528f-41f1-a058-732ec8ee4eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>bf9616bb-9e39-444a-be29-1e3b831a625f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-index</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>5718f3fe-8dd9-4351-b560-b69c16d00f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-multiple-selection</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>525af360-8e9f-4ce2-ab0c-a7dec84a942e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>37a250fe-9650-4832-a63e-33dbcc4719dc-43</value>
      <webElementGuid>ff3eba9a-451d-4c7c-9333-df6d983924ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>cf37ddeb-6b60-475a-a1b3-56a31b18130f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>72aa313a-6ad3-478b-a46d-063212b1dcf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUDIO/VISUAL EQUIPMENT - VIDEO PLAYER</value>
      <webElementGuid>4eb4828a-797a-4dc4-b56f-552ffb979899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;37a250fe-9650-4832-a63e-33dbcc4719dc-43&quot;)</value>
      <webElementGuid>6524ce0f-f280-4a83-b163-fbb965b4dbde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='37a250fe-9650-4832-a63e-33dbcc4719dc-43']</value>
      <webElementGuid>c24dccf5-783c-454d-9fd8-45ce898b3b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='815fd1f2-cd9e-4d97-9d43-070b16f75829']/li[34]</value>
      <webElementGuid>a6aee1a9-f192-4cb7-a28b-01223f408a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - TOUCH DISPLAY'])[1]/following::li[1]</value>
      <webElementGuid>9b558b32-e76a-4753-9214-b8331aeb489a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT - TELEVISION'])[1]/following::li[2]</value>
      <webElementGuid>6344a4bd-9369-4f23-b419-ad115438148b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDIO/VISUAL EQUIPMENT- PROJECTOR SCREEN'])[1]/preceding::li[1]</value>
      <webElementGuid>c7aa99b0-1dd7-4575-a31c-16da8adae154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUTOMOTIVE REPAIR EQUIPMENT'])[1]/preceding::li[2]</value>
      <webElementGuid>3e4bc0f8-f714-498b-96cb-bbba43fac34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AUDIO/VISUAL EQUIPMENT - VIDEO PLAYER']/parent::*</value>
      <webElementGuid>2de12683-eca3-46f0-8eaa-c8731ad269a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[34]</value>
      <webElementGuid>6a176f19-9495-4aaa-b49e-359e6a6970ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '37a250fe-9650-4832-a63e-33dbcc4719dc-43' and (text() = 'AUDIO/VISUAL EQUIPMENT - VIDEO PLAYER' or . = 'AUDIO/VISUAL EQUIPMENT - VIDEO PLAYER')]</value>
      <webElementGuid>c06a9147-fc4f-49cf-bc7d-9a539f4aa8f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
