<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_SCIENCELABORATORY EQUIPMENT</name>
   <tag></tag>
   <elementGuidId>4e85a257-31f1-40b0-9375-63a0ac82260e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[191]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8ebec743-9041-48e7-ad98-86a4c28100f9-51</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>990489a6-b3e6-450c-90ff-eae63afa763d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>84cb1f6c-aa24-4b4d-b73d-45114c7df0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9e267207-fd92-4e23-a0cf-d9b1c895d01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>8332d7d8-ee55-4887-b188-ed9e1af1dad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>51db483d-2f97-4c41-8835-5a8dee8bcc08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-index</name>
      <type>Main</type>
      <value>190</value>
      <webElementGuid>677e842c-ae9b-4ad5-a449-19c21a9c6727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-multiple-selection</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0205fad5-a600-4df4-ba1d-b4b4ace7e0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8ebec743-9041-48e7-ad98-86a4c28100f9-51</value>
      <webElementGuid>767aa04f-e44d-4f54-8349-9cd0e1c8cc57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9100cd69-8ef2-4e83-9553-8028dccfcbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>190</value>
      <webElementGuid>0fc0a04c-9c49-47d1-8a74-41280c27bdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SCIENCE/LABORATORY EQUIPMENT</value>
      <webElementGuid>6b171d94-f507-4f84-8a63-40510be2ea4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8ebec743-9041-48e7-ad98-86a4c28100f9-51&quot;)</value>
      <webElementGuid>1a8d177a-4f4f-4163-8525-cbe64b30b365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='8ebec743-9041-48e7-ad98-86a4c28100f9-51']</value>
      <webElementGuid>af2a7f85-14ff-4e07-8170-459432b757d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='a4780128-cd5f-4526-892f-9e52169ecfdb']/li[191]</value>
      <webElementGuid>4827b744-5345-4328-beb6-2290e18ad5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sar SY'])[1]/following::li[1]</value>
      <webElementGuid>89a27367-0622-48bb-af24-8b1034a1b6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RECREATIONAL EQUIPMENT - PLAYGROUND EQUIPMENT'])[1]/following::li[2]</value>
      <webElementGuid>4693c521-ea2e-4af4-bcb7-f7a35849c0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPED EQUIPMENT - AUDIO'])[1]/preceding::li[1]</value>
      <webElementGuid>fac230ae-9cf8-4b7c-828c-920f864506fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPED EQUIPMENT - SPECIAL NEEDS'])[1]/preceding::li[2]</value>
      <webElementGuid>0b1d81f3-2138-41f7-96e3-9731999d8151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SCIENCE/LABORATORY EQUIPMENT']/parent::*</value>
      <webElementGuid>8550e49e-ff23-48f1-8ec5-a679605fcccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[191]</value>
      <webElementGuid>e3000167-9ffa-4f6a-8d32-c7cdf398cb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '8ebec743-9041-48e7-ad98-86a4c28100f9-51' and (text() = 'SCIENCE/LABORATORY EQUIPMENT' or . = 'SCIENCE/LABORATORY EQUIPMENT')]</value>
      <webElementGuid>4d64074c-14cf-4df7-b485-ac07d42d2a6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
