<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Assign Site Name</name>
   <tag></tag>
   <elementGuidId>e4d5f57c-ee39-437c-a637-c398885d4992</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#k-grid2-checkbox0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f370a1d6-c054-4e51-9829-b76bd745a6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox ng-star-inserted</value>
      <webElementGuid>6b71eed0-28e2-4171-a390-7d9cbd9a87d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-item-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c50e63e0-b26b-4cbc-ad8b-4705c23b3bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-grid2-checkbox0</value>
      <webElementGuid>6111f0cb-fb6d-407e-9f33-0a03bb8a64ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f65d0ff9-4289-411c-9adc-bc9fd7ceabe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-grid2-checkbox0&quot;)</value>
      <webElementGuid>c2380016-78a2-4e82-b306-034ae1e9d0ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-grid2-checkbox0']</value>
      <webElementGuid>4adb98b3-c749-46cd-b06d-b17290de4fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-grid[@id='addInventoryGrid']/div/kendo-grid-list/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>3101a594-9d71-466b-92f8-6a3716a7b45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>c75267db-97d5-47cd-9437-b6387828db71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-grid2-checkbox0' and @type = 'checkbox']</value>
      <webElementGuid>eb1303af-719b-4c09-85d4-3c849eff9436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
