<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Room_field</name>
   <tag></tag>
   <elementGuidId>0bffb39d-8885-442c-802e-d20e2928c9a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='room']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#room</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ff9aa72-3cb3-42db-b93c-1ecd4328fffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
      <webElementGuid>51bbbf17-9e17-4da9-96b9-fb333a3814a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>f80f1185-947b-470a-9741-37d0a0babec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>room</value>
      <webElementGuid>c712c44f-ba23-4fed-9585-ba4b2d13d279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter where your technician can find you (room number, building, etc.)...</value>
      <webElementGuid>a1f47a76-cc8b-46f0-9b26-1dc57e779dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ca1c063-6021-4692-890f-0b3519ef2d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>e12daf03-e711-46ba-97fe-2ad1140d4592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>000000 510</value>
      <webElementGuid>8fbf94c2-f90a-4bde-91f7-d53cf6335238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;room&quot;)</value>
      <webElementGuid>e7e69cbf-11ab-4a0c-bd98-66f79667ddec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='room']</value>
      <webElementGuid>7baea12c-69f9-40a4-afb3-c0915baabf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b1b0e1a6-1a9e-4ff4-908a-2f38948102cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'room' and @placeholder = 'Please enter where your technician can find you (room number, building, etc.)...' and @type = 'text']</value>
      <webElementGuid>7aef82e1-389b-41da-8558-24b7c61566fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
