<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Service Hours</name>
   <tag></tag>
   <elementGuidId>654d2c2c-a815-4586-8208-763c3b34fc41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/div/ul[2]/li[3]/ul/li/kendo-menu[3]/ul/li/div/a/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b17ec61d-1f29-457d-b747-751d02a2732a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-remove-margin-bottom</value>
      <webElementGuid>c458f677-89db-4969-91ac-460bb0515e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Service Hours</value>
      <webElementGuid>9da85985-0100-40e7-b816-8cb4c40349a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/div[@class=&quot;row gh-100-width&quot;]/ul[@class=&quot;navbar-nav flex-row ml-md-auto d-none d-md-flex&quot;]/li[@class=&quot;dropdown gh-admin-navbar-button&quot;]/ul[@class=&quot;gh-sub-menu&quot;]/li[1]/kendo-menu[3]/ul[@class=&quot;k-widget k-reset k-header k-menu k-menu-vertical&quot;]/li[@class=&quot;k-item k-menu-item k-first k-last&quot;]/div[@class=&quot;row gh-no-margin gh-100-width text-center&quot;]/a[@class=&quot;col-xl-12 gh-navigation-hidden-link&quot;]/p[@class=&quot;gh-remove-margin-bottom&quot;]</value>
      <webElementGuid>8940a843-3ddb-4f41-acf9-eb1531a951ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ul[2]/li[3]/ul/li/kendo-menu[3]/ul/li/div/a/p</value>
      <webElementGuid>bbffe0c0-ad59-4b01-b32f-6d31f9ac828d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Service Hours']/parent::*</value>
      <webElementGuid>e6e21410-7255-4d4c-9f6c-fca0035b2054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-menu[3]/ul/li/div/a/p</value>
      <webElementGuid>031771a1-8cd0-414c-a7f7-f04464ecb9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Service Hours' or . = 'Service Hours')]</value>
      <webElementGuid>04175813-2453-42d5-8dd7-e32666bfd067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
