<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Site_Field</name>
   <tag></tag>
   <elementGuidId>0c39e4e7-585e-451d-8bcd-0e2e7a6b9fe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#k-80cdd775-0461-419e-bca0-bcbc897c41a2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='newTicketDetailsContainer']/div[2]/div/dynamic-form/div/form-select-site/div/div/div/form/div/div[2]/div/autocomplete/div/kendo-autocomplete/kendo-searchbar/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e47c7f6e-3f0c-4572-9836-2a1be4c8f991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>06955e28-c8cb-4388-842c-609a5d797097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>736686b7-fee1-4b11-bec9-b9ab07d1ae51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-80cdd775-0461-419e-bca0-bcbc897c41a2</value>
      <webElementGuid>63c8c626-124b-42e8-937a-148263bdd8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing the name of the site to get a list of possible matches...</value>
      <webElementGuid>88019fa7-d861-4714-b9f0-dc0ecefd82b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>e3658e5d-a6d2-4ab2-9d25-116c12590d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e8f48818-8619-4afc-a24b-492f55f53bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>5f568810-e9f3-4e4e-b2cb-cc31cc075e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e95296e5-6151-4471-b8f1-47740f93b5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>abb48441-c5ac-49c4-bb72-b6b7b284927f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9c2ba8a5-b6e8-4e74-b7ea-96fdf8bff437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ec54ef4-e4bd-4628-a831-1ca48295e114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b56f3d74-bffd-476c-ad88-4febd68cad8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>bc0c9fe5-bf49-47c1-9600-dd61e79ad82e</value>
      <webElementGuid>1e41eb74-2471-4e50-9bf4-6c437731fb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>7bfa5b80-bff3-4b4f-b129-97ec9bd65134-undefined</value>
      <webElementGuid>16ed7b3c-3b26-4cd6-9dce-39888b5f0f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-80cdd775-0461-419e-bca0-bcbc897c41a2&quot;)</value>
      <webElementGuid>b83ff424-a2f5-4ac1-b16b-2fed14200a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-80cdd775-0461-419e-bca0-bcbc897c41a2']</value>
      <webElementGuid>0867e92d-5174-4fbd-91cc-552947e0a388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newTicketDetailsContainer']/div[2]/div/dynamic-form/div/form-select-site/div/div/div/form/div/div[2]/div/autocomplete/div/kendo-autocomplete/kendo-searchbar/input</value>
      <webElementGuid>51172fa1-0514-48a8-a094-2adba5f525dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-searchbar/input</value>
      <webElementGuid>e474774c-1b72-4df1-8867-eb4398de1843</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
