<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>POST CreateUser</name>
   <tag></tag>
   <elementGuidId>e8b7d1b4-39c3-4dca-b93f-343099b40dab</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n\t\&quot;loginName\&quot;: \&quot;pepe\&quot;,\n\t\&quot;Password\&quot;: \&quot;Ble\&quot;,\n\t\&quot;Active\&quot;: \&quot;true\&quot;,\n\t\&quot;UserTypeId\&quot;: 2,\n\t\&quot;FirstName\&quot;: \&quot;Pepe\&quot;,\n\t\&quot;MiddleName\&quot;: \&quot;E\&quot;,\n\t\&quot;LastName\&quot;: \&quot;Toro\&quot;,\n\t\&quot;Email\&quot;: \&quot;bjka@jkasncom\&quot;,\n\t\&quot;PhoneNumber\&quot;: \&quot;5128000000\&quot;,\n\t\&quot;CreateById\&quot;: \&quot;2\&quot;\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${HHD_API_Bearer}</value>
      <webElementGuid>7a31e95f-87d2-4f54-a34e-4fa4542bff0d</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>bef25a20-2d6e-42d2-bdff-b42fffbc20fb</webElementGuid>
   </httpHeaderProperties>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${HHD_API_Url}/api/User/CreateUser</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.HHD_API_Url</defaultValue>
      <description></description>
      <id>879ba35d-6397-499e-a3f6-f878f3d3db2c</id>
      <masked>false</masked>
      <name>HHD_API_Url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.HHD_API_Bearer</defaultValue>
      <description></description>
      <id>f83bce33-8a63-44df-86fb-81f76713f321</id>
      <masked>false</masked>
      <name>HHD_API_Bearer</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
